# Generated by Django 5.0.1 on 2024-01-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, default=1234567890),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
