# Generated by Django 4.2.6 on 2024-04-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
