# Generated by Django 4.2.6 on 2024-04-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_rename_manager_id_project_manager'),
        ('accounts', '0008_customuser_is_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.project'),
        ),
    ]
