# Generated by Django 4.2.6 on 2024-03-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='manager_id',
        ),
    ]
