# Generated by Django 4.2.6 on 2024-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_project_project_status_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=20),
        ),
    ]
