# Generated by Django 4.2.6 on 2024-04-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_project_document_alter_task_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
